### ISSUE TITLE
Is there a data leakage?

### ISSUE THREAD

**Issue by hexiaoyupku** [tanthongtan/dv-cosine#1]
hi tanthongtan, 
Thanks for your work! 
The paper says ' The document vectors are learned using all the documents in the dataset (train, **test** and unlabeled documents)'. I was wondering if it's a kind of data leakage, because the model saw test data in advance. 
Have you ever tried exclude the test data to train document vectors?

**Comment by tanthongtan** [comment]
Hello, thanks for your interest in our work! Also, sorry for the late reply. Yes it is definitely possible to do some kind of 'inference' style learning of document vectors for the test documents where you would freeze the weights of the network during testing and only do SGD on the new test documents as described in (Le and Mikolov, 2014). I may implement this in the future. 

However, training on the test documents in this case is justified as no labels are involved and it is also what other pieces of related work have done. For example, in (Lau and Baldwin, 2016) they mention "We use all documents in the development and test set (and potentially more background documents, where explicitly mentioned) to train doc2vec. Our rationale for this is that the doc2vec training is completely unsupervised, i.e. the model takes only raw text and uses no supervised or annotated information, and thus there is no need to hold out the test data, as it is unlabelled."

References
1. Jey Han Lau and Timothy Baldwin. 2016. An empirical evaluation of doc2vec with practical insights into document embedding generation. arXiv preprint arXiv:1607.05368.
2. Quoc V. Le and Tomas Mikolov. 2014. Distributed representations of sentences and documents. In Proceedings of the 31st International Conference on Machine Learning, pages 1188–1196.

**Comment by hexiaoyupku** [comment]
Thanks for your reply! I understand what you mean. Looking forward for your further experiments and study!
